### ISSUE TITLE
Fix crashes in v1.4.7

### ISSUE THREAD

**Issue by bogdan-evtushenko** [xorum-io/codeforces_watcher#108]

**Comment by yevhenii-kanivets** [comment]
Looks like this one only happens on Android 5.1: https://console.firebase.google.com/u/0/project/codeforces-watcher/crashlytics/app/android:com.bogdan.codeforceswatcher/issues/3bb7bf68ae1c549df936cf59a9bf7293.

Need to check.

**Comment by yevhenii-kanivets** [comment]
@bogdan-evtushenko there are 3 or 4 active crashes in Firebase, can you check them today? You can do fixes right in KMP branches, just reference this issue in commit message.
