### ISSUE TITLE
IOS pre-release fixes.

### ISSUE THREAD

**Issue by bogdan-evtushenko** [xorum-io/codeforces_watcher#139]
Works great, sometimes looks better than Android version 👍 
But fixes can be done:
1. Remove tags when you share actions (Ex. : 
![image](https://user-images.githubusercontent.com/34541299/80464771-f33e1380-8942-11ea-8a87-157133d298d2.png)
)
2. Small UI bug in filters contests(video will be in slack).
3. Filtering problem fix: for now user can't find problem by id and letter, for example 1234E, 516F...
4. Strange UI behaviour in problems filtering? (video will be added).

**Comment by yevhenii-kanivets** [comment]
@bogdan-evtushenko all should be fixed now, could you quickly check one more time, please?
