### ISSUE TITLE
Fix "Users" screenshot for iPhone 8 Plus.

### ISSUE THREAD

**Issue by yevhenii-kanivets** [xorum-io/codeforces_watcher#144]
![Users iOS (iPhone 8 Plus)](https://user-images.githubusercontent.com/11427267/80949987-ba4be600-8dfd-11ea-9164-1ec0e1f56256.png)

**Comment by MatyashDen** [comment]
+ update ipad screenshots
![image](https://user-images.githubusercontent.com/42153507/81062627-03279b80-8edf-11ea-906a-adf3c20b6413.png)

**Comment by yevhenii-kanivets** [comment]
Also Contest / Actions for iPhone X need to be updated.
