### ISSUE TITLE
Add missing translation for ukranian, russian, hindi.

### ISSUE THREAD

**Issue by yevhenii-kanivets** [xorum-io/codeforces_watcher#145]

**Comment by MatyashDen** [comment]
Hindi translation is task for our users?

**Comment by yevhenii-kanivets** [comment]
@MatyashDen yes, I'll ping guys who helped us previous time. Maybe they can help us this time too.

**Comment by MatyashDen** [comment]
don't forget for ios specific strings

**Comment by yevhenii-kanivets** [comment]
@nishitkshah hi, I hope you are doing well 😉Can you help us translate another dozen of string to Hindi?

```
    <string name="no_favourite_problems">You don’t have any favourite problems yet.\nAdd the first one using «∞» at the bottom of the screen.</string>
    <string name="problems_on_the_way">Problems on the way to your device…</string>
    <string name="search_for_problems">Search for problems…</string>
    <string name="no_browser_has_been_found">No browser has been found, try to install one.</string>
    <string name="filters">Filters</string>
    <string name="no_contests_found">No contests found</string>
    <string name="click_to_see_details">Click to see details</string>
```

**Comment by yevhenii-kanivets** [comment]
@MatyashDen could you also post here iOS specific strings needed to be translated to Hindi, please?

**Comment by MatyashDen** [comment]
"ago" = "ago";
"Has been added to your calendar" = "Has been added to your calendar";
"Can't add contest to Calendar without permission" = "Can't add contest to Calendar without permission";
"OK" = "OK";
"Official Codeforces rules" = "Official Codeforces rules";
"Apple isn't a sponsor of any contests conducted on Codeforces" = "Apple isn't a sponsor of any contests conducted on Codeforces";
"Add user" = "Add user";
"Enter user handle" = "Enter user handle";
"Done" = "Done";
"share_text" = "%@ - %@\n\nShared through Codeforces Watcher. Find it on App Store.";
"Check upcoming programming contests" = "Check upcoming programming contests";

**Comment by MatyashDen** [comment]
"yes" = "Yes!";
"rate_us_first_title" = "Enjoying our Codeforces WatchR App?";
"rate_us_second_title" = "Would you mind giving us some feedback?";
"rate_us_third_title" = "How about a rating on the App Store, then?";
"not_really" = "Not really";
"no_thanks" = "No, thanks";

**Comment by nishitkshah** [comment]
Is this still pending? I can try to get some time next weekend.

**Comment by yevhenii-kanivets** [comment]
@nishitkshah yes, that would be nice 🙏

**Comment by MatyashDen** [comment]
@nishitkshah 
How is the translation going?

**Comment by yevhenii-kanivets** [comment]
Or maybe @Brijesh1in has some time for these strings 😉

**Comment by Brijesh1in** [comment]
Okay Sure !
But Can you please tell me the formats @yevhenii-kanivets @MatyashDen  or where are those files ? I am not that good in using github .

**Comment by yevhenii-kanivets** [comment]
@Brijesh1in thanks 🙏 In this ticket you can find all the strings we need translations for (3 messages in total). You can include translation in this ticket directly in the same format as messages are written, changing English translation to Hindi.

For example:
`<string name="no_favourite_problems">Hindi translation here</string>`
`"rate_us_first_title" = "Hindi translation here";`

**Comment by nishitkshah** [comment]
Sorry, I'm a little busy these days. Didn't get chance to work on this last weekend. Thanks @Brijesh1in for the help. Let me know in case I can be of help again.

**Comment by Brijesh1in** [comment]
<string name="no_favourite_problems">आपके पास अभी कोई पसंदीदा सवाल नहीं है ।\n अपना पहला पसंदीदा सवाल स्क्रीन में नीचे दिए गए «∞» बटन पर क्लिक करके जोड़ें ।</string>
    <string name="problems_on_the_way">सवाल आपके डिवाइस पे लोड हो रहा है...</string>
    <string name="search_for_problems">सवाल खोजे...</string>
    <string name="no_browser_has_been_found">कोई ब्राउज़र नहीं पाया गया , कृपया कोई इंस्टॉल करें।</string>
    <string name="filters">Filters</string>
    <string name="no_contests_found">कोई प्रतियोगिता नहीं पाया गया</string>
    <string name="click_to_see_details">विवरण देखने के लिए क्लिक करें</string>

@yevhenii-kanivets @MatyashDen I have translated the first one . I'll try do others by tomorrow .

**Comment by Brijesh1in** [comment]
"ago" = "पहले ";
"Has been added to your calendar" = "आपके कैलेंडर में जोड़ दिया गया";
"Can't add contest to Calendar without permission" = "बिना स्वीकृति के प्रतियोगिता को कैलेंडर में नहीं जोड़ सकते ";
"OK" = "OK";
"Official Codeforces rules" = "कोडफ़ोर्सेज़ के आधिकारिक नियम";
"Apple isn't a sponsor of any contests conducted on Codeforces" = "ऐपल कोडफ़ोर्सेज़ पर आयोजित किसी भी प्रतियोगिता का प्रायोजक नहीं है ";
"Add user" = "यूज़र जोड़ें";
"Enter user handle" = "यूज़र हैंडल डाले";
"Done" = "Done";
"share_text" = "%@ - %@\n\n यह कोडफ़ोर्सेज़ वाचर के द्वारा शेयर किया गया है । इसे ऐप स्टोर पे प्राप्त करें ।";
"Check upcoming programming contests" = "आने वाली प्रोग्रैमिंग प्रतियोगिताएँ देखे";
"contests_explanation" = "प्रतियोगिताएँ आपके डिवाइस पे लोड की जा रही हैं...";

@yevhenii-kanivets @MatyashDen  The second one is also done . Just one thing where are you using the word "ago" ? I tried to find it in the app but I couldn't :( . So if you tell me maybe I can come up with something that describes it better .

**Comment by Brijesh1in** [comment]
"yes" = "हाँ!";
"rate_us_first_title" = "क्या आप हमारा कोडफ़ोर्सेज़ ऐप एंजोय कर रहे हैं ?";
"rate_us_second_title" = "क्या आप हमें फ़ीडबैक देना चाहेंगे?";
"rate_us_third_title" = "फिर ऐप स्टोर पे रेटिंग देना कैसा रहेगा ?";
"not_really" = "नहीं ";
"no_thanks" = "नहीं , धन्यवाद ।";

"chart_info" = " = %@ (%@) \n Place: %@ \n %@ \n %@ ";

@yevhenii-kanivets @MatyashDen Can you please describe what is "Place" in chart info ?

**Comment by MatyashDen** [comment]
@Brijesh1in 
We are using "ago" in actions
![image](https://user-images.githubusercontent.com/42153507/82421718-19f6f200-9a8a-11ea-982b-f988b91d0dc4.png)

**Comment by MatyashDen** [comment]
@Brijesh1in 
![image](https://user-images.githubusercontent.com/42153507/82422003-8ffb5900-9a8a-11ea-91bb-c158e65670a8.png)
We updated chart info and here we have "Place", but i think it's better to rename it to "Rank".
So, let's update this string to:
"chart_info" = " = %@ (%@) \n Rank: %@ \n %@ \n %@ ";

**Comment by Brijesh1in** [comment]
@yevhenii-kanivets @MatyashDen The whole translation is done .
@nishitkshah Can you please review it ?

**Comment by MatyashDen** [comment]
@Brijesh1in 
Great!
Thank you very much for your help🙏🏻

**Comment by yevhenii-kanivets** [comment]
@Brijesh1in thanks a lot 🙏 Do you have an account on Codeforces (so I can mention you in next post)?

**Comment by nishitkshah** [comment]
Overall looks good to me. Thanks @Brijesh1in . NIT : no_contests_found text should be "koi pratiyogita nahi *payi gayi*".

**Comment by nishitkshah** [comment]
That is "कोई प्रतियोगिता नहीं पाई गई"

**Comment by nishitkshah** [comment]
Or "कोई प्रतियोगिता नहीं मिली" which is shorter

**Comment by Brijesh1in** [comment]
Yeah , right @nishitkshah it is a bit shorter .
@yevhenii-kanivets @MatyashDen If you want to improve it you can . By the way previous one is also okay .

**Comment by Brijesh1in** [comment]
> @Brijesh1in thanks a lot 🙏 Do you have an account on Codeforces (so I can mention you in next post)?

Yeah it's "TiredOfLife" but no need to mention it :)

**Comment by MatyashDen** [comment]
@Brijesh1in @nishitkshah 
Thank you a lot, guys🤝
