### ISSUE TITLE
Fixes after testing.

### ISSUE THREAD

**Issue by bogdan-evtushenko** [xorum-io/codeforces_watcher#172]
Android: 
- looks strange, that in Actions showed only one of two item (or Pinned item, or FeedbackItem).
- Need to update link to the contests when user adds some contest to Google Calendar (for now it is always link to the Codeforces contests)
- New design for adding users is great 👍 

IOS:
- nitpick from video
- 1 paragraph from Android

**Comment by yevhenii-kanivets** [comment]
@bogdan-evtushenko thanks a lot for testing 🙏 

@MatyashDen ⬇️ 

1 paragraph is a temporary workaround, which will be fixed once we add other feed sources (YouTube, for example).

Agree about link: Let's fix if possible.

Nitpick from video is valid one. Let's fix if possible.
