### ISSUE TITLE
Use "Get News" endpoint.

### ISSUE THREAD

**Issue by yevhenii-kanivets** [xorum-io/codeforces_watcher#188]
There is a new backend and new endpoint to fetch news. Run it locally for now, and I will try to host it this week.

**Comment by yevhenii-kanivets** [comment]
Analytics:
`actions_fetch`
`actions_fetch_success`
`actions_fetch_failure`

**Comment by MatyashDen** [comment]
> Analytics:
> `actions_fetch`
> `actions_fetch_success`
> `actions_fetch_failure`

@yevhenii-kanivets maybe news, not actions?

**Comment by yevhenii-kanivets** [comment]
@MatyashDen you are right 👍
