### ISSUE TITLE
Add Analytics.

### ISSUE THREAD

**Issue by yev-kanivets** [xorum-io/codeforces_watcher#237]
Ping @yevhenii-kanivets once all other tasks are ready to decide on which analytics is important for Doyle features.

**Comment by yev-kanivets** [comment]
1. `sign_in_opened` when user opens "Sign In" screen.
2. `sign_in_done` when user signed in successfully.
3. `sign_up_opened` when user opens "Sign Up" screen.
4. `sign_up_done` when user signed up successfully.
5. `verify_opened` when user opens "Verify Account" screen.
6. `verify_done` when user verified account successfully.
7. `log_out` when user logged out.
8. `restore_password` when user restores password.

**Comment by MatyashDen** [comment]
fetch_users_failure
fetch_users_success
