### ISSUE TITLE
Filter problems by tags.

### ISSUE THREAD

**Issue by yev-kanivets** [xorum-io/codeforces_watcher#251]
# Description

Allow users to filter problems by tags. Problem's tags can be easily retrieved from https://codeforces.com/api/problemset.problems (endpoint is already implemented).

Problem should be marked with all checked tags to be displayed in filter. Filters should be persisted between launches in Settings (SharedPrefs).

Filtering logic should be implemented in `common` module, so it later can be reused by iOS app. For better understanding of architecture, which is used in both apps (Redux) check out the following articles:
- https://medium.com/xorum-io/redux-for-android-with-kotlin-in-practice-part-1-initial-setup-8f1a417d466e
- https://medium.com/xorum-io/redux-for-android-with-kotlin-in-practice-part-2-fetching-data-from-network-676a61647f66
- https://medium.com/xorum-io/redux-for-android-with-kotlin-in-practice-part-3-final-touches-f7861f77d754

You can add `filters` to `ProblemsState` and reinit them as unique values of tags taken from problems when they are set in `problemsReducer`.

# Design

Add filter icon to the right side of toolbar in Problems tab. Icon is already added to app.

When clicked open this screen: https://www.figma.com/file/l6SIUlv0M74QAAeRVXeFNh/algoris.me?node-id=473%3A1214.

**Comment by dush1729** [comment]
@yevhenii-kanivets Please assign this to me
