### ISSUE TITLE
Translate new strings to Hindi

### ISSUE THREAD

**Issue by yev-kanivets** [xorum-io/codeforces_watcher#429]
The translation is needed for all strings highlighted in red. Put it [here](https://github.com/xorum-io/codeforces_watcher/blob/dev/app/src/main/res/values-hi/strings.xml)

<img width="713" alt="Capture d’écran 2022-05-27 à 10 12 28" src="https://user-images.githubusercontent.com/11427267/170650255-43d50f7c-d261-4f03-96b9-fe44d36e92e4.png">
<img width="708" alt="Capture d’écran 2022-05-27 à 10 12 37" src="https://user-images.githubusercontent.com/11427267/170650262-606c2fa6-5ccc-4be7-b224-213deb6580b7.png">
<img width="1046" alt="Capture d’écran 2022-05-27 à 10 12 44" src="https://user-images.githubusercontent.com/11427267/170650265-37e7d5c5-5cd5-42ed-b150-8fa6bbcfbcd5.png">
<img width="465" alt="Capture d’écran 2022-05-27 à 10 12 48" src="https://user-images.githubusercontent.com/11427267/170650267-cbc2d43d-c6b7-4073-a10f-776a62ba673e.png">
<img width="1118" alt="Capture d’écran 2022-05-27 à 10 12 54" src="https://user-images.githubusercontent.com/11427267/170650269-5ef7e917-8baa-4649-96d8-a34644768fe3.png">
<img width="810" alt="Capture d’écran 2022-05-27 à 10 39 56" src="https://user-images.githubusercontent.com/11427267/170653093-6ab481c4-da6f-41c5-bb85-e33660b5b00f.png">

**Comment by yev-kanivets** [comment]
Hey @nishitkshah @Brijesh1in, you helped us with Hindi localization previously 🙏 Will you be able to translate a few more strings (only those highlighted in red)?

**Comment by Brijesh1in** [comment]
@yev-kanivets Sure will do that on this weekend .

**Comment by yev-kanivets** [comment]
@Brijesh1in thanks a lot 🙏

**Comment by Brijesh1in** [comment]
Hey Sorry ! I forgot . A bit busy these days . Getting settled in a new place . Can you please send the resources in text format ?
It would be easy for me to make changes .

**Comment by yev-kanivets** [comment]
@Brijesh1in sure, I understand. Here are the strings in text format:

```
<resources>
  <string name="contests_explanation">Contests are on the way to your device…</string>
  <string name="see_details">See details</string>
  <string name="update_explanation">Huge redesign, mentors &amp; more!</string>
  <string name="contest_month_format">LLLL</string>

  <string name="delete_account">Delete account</string>
  <string name="do_not_delete">Do not delete</string>
  <string name="delete_account_warning">Warning! This action is irreversible.</string>
  <string name="delete_account_explanation">"If you delete your account, you will no longer be able to use the full functionality of the application, in particular:
- personal profile
- rating tracking
- notifications about rating updates
- mentorship program
- algois.me special events
- participating in Challenges
- badges, medals, stats and more

You will still be able to use basic functionality of the application, which is available without registration, in particular, follow other users, watch contests (including Challenges, but without the ability to participate), view and save problems, read news.

Please note that without account, your content will not be able to sync, so if you uninstall the app, your data will not be saved and may be lost."</string>
  <string name="delete_account_hint">Account cannot be restored.\nThink wisely before doing it.</string>
  <string name="delete_account_sure">Are you sure?\nMark the checkbox to confirm your intentions.</string>
  <string name="want_to_delete_account">I want to delete my account</string>

  <string name="login">Login</string>
  <string name="login_to_identify_explanation">Login to identify and get instant push notifications about rating updates</string>
  <string name="who_are_you">Who are you?</string>

  <string name="rating_new">Rating</string>
  <string name="max_rating_new">Max Rating</string>
  <string name="contribution_new">Contribution</string>
  <string name="view_profile">View profile</string>

  <string name="lost_access_to_mail">Lost access to mail?</string>
  <string name="restore_password">Restore password</string>
  <string name="you_will_get_an_email_with_instructions_for_account_recovery">You will get an email with instructions for account recovery</string>

  <string name="check_your_box">Check your inbox.</string>
  <string name="open_mail_hint">Tap to open your mail app</string>
  <string name="open_mail">Open mail</string>
  <string name="back_to_sign_in">Back to sign in</string>
  <string name="check_your_spam_folder">If you haven’t received a message within 5 minutes, check your Spam folder.</string>
  <string name="mail_app_not_found">Mail app not found</string>

  <string name="to_verify_please_change_your_last_name_start">To verify that account belongs to you, please, change your English ”Last name” in your</string>
  <string name="to_verify_please_change_your_last_name_path">Profile - Settings - Social</string>
  <string name="to_verify_please_change_your_last_name_end">to this value:</string>
  
  <string name="agree_with_the_conditions_and_privacy_policy_start">I agree with the</string>
  <string name="agree_with_the_conditions_and_privacy_policy_end">and the</string>
</resources>
```

**Comment by Brijesh1in** [comment]
<resources>
  <string name="contests_explanation">प्रतियोगिता लोड हो रहा है</string>
  <string name="see_details">विस्तार में देखे</string>
  <string name="update_explanation">बड़े बदलाव , परामर्श दाता  &amp; और भी !</string>
  <string name="contest_month_format">LLLL</string>

  <string name="delete_account">खाता मिटाएं</string>
  <string name="do_not_delete">ना हटायें</string>
  <string name="delete_account_warning">सावधान! इसे फिर से नहीं बदला जा सकता है</string>
  <string name="delete_account_explanation">"अगर आप अपना खाता मिटातें हैं तो आप ऍप की सारी सुविधाओं का इस्तेमाल नहीं कर पाएंगे। , विशेषत:
- व्यक्तिगत प्रोफाइल
- रेटिंग की जानकारी 
- रेटिंग बदलाव की सूचना 
- परामर्श लेना 
- algois.me के विशेष कार्यक्रम 
- चुनौतियों में भाग लेना 
- बिल्ला , पदक , आंकड़े और ... 


आप फिर भी ऍप की सामान्य सुविधाओं का इस्तेमाल कर पाएंगे जो की बिना पंजीकरण के उपलब्ध होंगे , जैसे की दूसरे यूजर को फॉलो करना , प्रतियोगिताएं देखना (चुनौतियां समेत , लेकिन इनमे भाग लेने की सुविधा नहीं होगी) , सवाल देखना और सेव करना , समाचार (न्यूज़) पढ़ना 

कृपया ध्यान दे की अगर बिना खाते के आपका कंटेंट सिंक में नहीं रहेगा और अगर आप ऍप अनइंस्टॉल करते हैं तो हो सकता है की आपका डाटा सेव ना हो और ये खो जाये "</string>
  <string name="delete_account_hint">आपके खाते को पुनः वापस नहीं लाया जा सकता।\nऐसा करने से पहले पुनः सोचे </string>
  <string name="delete_account_sure">आपने निश्चय कर लिया है ??\nपुष्टि करने के लिए बॉक्स में टिक करे। </string>
  <string name="want_to_delete_account">मुझे अपना खाता मिटाना है। </string>

  <string name="login">लॉगिन </string>
  <string name="login_to_identify_explanation">पहचान बताने के लिए लॉगिन करें और नयी रेटिंग आने पर तुरंत पुश नोटिफिकेशन्स पाएं </string>
  <string name="who_are_you">आप कौन हैं ?</string>

  <string name="rating_new">रेटिंग </string>
  <string name="max_rating_new">अधिकतम रेटिंग </string>
  <string name="contribution_new">योगदान </string>
  <string name="view_profile">प्रोफाइल देखें </string>

  <string name="lost_access_to_mail">आप अपना ईमेल नहीं देख पा रहे हैं ?</string>
  <string name="restore_password">पासवर्ड पुनः प्राप्त करें</string>
  <string name="you_will_get_an_email_with_instructions_for_account_recovery">आप को एक ईमेल प्राप्त होगा जिसमें खाते को पुनः प्राप्त करने के निर्देश होंगे </string>

  <string name="check_your_box">अपना इनबॉक्स चेक करें। </string>
  <string name="open_mail_hint">अपना ईमेल खोलने के लिए टैप करें</string>
  <string name="open_mail">मेल खोलें</string>
  <string name="back_to_sign_in">साइन इन पर जाएं  </string>
  <string name="check_your_spam_folder">अगर आपको 5 मिनट में मैसेज नहीं मिलता है तो कृपया अपना स्पैम फोल्डर देखें </string>
  <string name="mail_app_not_found">मेल ऍप नहीं मिला </string>

  <string name="to_verify_please_change_your_last_name_start">उस खाते को सत्यापित करने के लिए की यह खाता आपका है  कृपया अपना अंग्रेजी "अंतिम नाम" यहाँ बदले r</string>
  <string name="to_verify_please_change_your_last_name_path">प्रोफाइल  - सेटिंग - सोशल</string>
  <string name="to_verify_please_change_your_last_name_end">इस नाम से :</string>
  
  <string name="agree_with_the_conditions_and_privacy_policy_start">मैं सहमत हूँ </string>
  <string name="agree_with_the_conditions_and_privacy_policy_end">और </string>
</resources>

**Comment by yev-kanivets** [comment]
@Brijesh1in thanks a lot, those two strings contain a special symbol and format placeholder, no need to translate them.
