### ISSUE TITLE
Fix minor issues in problems tab.

### ISSUE THREAD

**Issue by bogdan-evtushenko** [xorum-io/codeforces_watcher#83]
1) Fix lagging UI when fetching problems.
2) Check why not all problems add to favourite, when click on them fast(3 or more in a raw).

**Comment by bogdan-evtushenko** [comment]
1) Fix  lagging UI when fetching problems.
2) Check why not all problems add to favourite, when click on them fast(3 or more in a raw).

**Comment by bogdan-evtushenko** [comment]
I invented obvious refactoring, I'll do it later...

**Comment by yevhenii-kanivets** [comment]
@bogdan-evtushenko figured out in this case :)
